### ISSUE TITLE
Reporte del Enlace De Descarga del Editor

### ISSUE THREAD

**Issue by Zen-xP** [lenguaje-latino/latino-editor#4]
Hola, el archivo de [descarga (Instalador y Archivo Portable)](https://github.com/lenguaje-latino/latino-editor/#windows) para Windows a dejado de funcionar o a sido eliminado, existe alguna solucion ?
![image](https://user-images.githubusercontent.com/70062021/163690497-a5270578-f5ba-40b3-a37d-4a90f42d9b89.png)

**Comment by enzonotario** [comment]
Buenas! Acabo de corregir los links, gracias por reportarlo.

Además, se encuentra disponible una versión online temporalmente en: https://latinoeditor.enzonotario.me/
