### ISSUE TITLE
Editor no funciona con Firefox

### ISSUE THREAD

**Issue by guizans** [lenguaje-latino/latino-editor#8]
Hola.

He probrado el editor y sobre Firefox no funciona, no puedo cargar archivos del ordenador, ni guardar ni ejecutar el Hola Mundo que viene. En Chromium funciona perfectamente.

Un saludo.

**Comment by enzonotario** [comment]
Hola,

En mi caso si funciona la ejecución:
![image](https://user-images.githubusercontent.com/10469299/223245647-94a549e8-94bf-4f25-9406-d3ee55790340.png)

Si la ejecución no te funciona, por favor adjuntá imágenes de las pestañas Consola/Red del Inspector.

Respecto a las funcionalidades extras del Menú (abrir/guardar archivos, etc), efectivamente no funciona. Gracias por reportarlo, aunque considero que no amerita dedicación, teniendo en cuenta que funciona perfectamente en Chromium/Chrome. Queda pendiente por si alguien está dispuesto a solucionarlo, o eventualmente en alguna actualización se solucionará.

Cierro el issue. Si tienes más información sobre el error de ejecución (que no pude reproducir), puedes abrirlo nuevamente.

Saludos!
